[client]
user_agent = "postwoman@sample/0.2.0"

[route.healthcheck]
url = "https://api.alemi.dev/"

[route.benchmark]
url = "https://api.alemi.dev/look/into/the/void"
extract = { type = "discard" }

[route.debug]
url = "https://api.alemi.dev/debug"
method = "PUT"
headers = [
	"Content-Type: application/json",
	"Authorization: Bearer ${PW_TOKEN}",
]
query = [
	"body=json",
	"cache=0"
]
body = { hello = "world!", success = true }
extract = { type = "body" }

[route.payload]
url = "https://api.alemi.dev/debug"
method = "POST"
body = '''{
	"complex": {
		"json": "payloads",
		"can": "be",
		"expressed": "this",
		"way": true
	}
}'''
extract = { type = "body" }

[route.cookie]
url = "https://api.alemi.dev/getcookie"
method = "GET"
extract = { type = "header", key = "Set-Cookie" }
